services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./lunch_app:/opt/lunch_app/lunch_app
    command: python -m uvicorn lunch_app.app:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
  
  db:
    image: postgres:13
    container_name: lunch_app_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  lunch_app:
  postgres_data:
